
export const PROCUCTS = [
  {
    id: 1,
    title: "iPhone 14 5G",
    uploadedDate: new Date(),
    description: `The iPhone 14 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 6.06 inches diagonally (actual viewable area is less).`,
    price: 1129,
    sellerName: "Apple",
    imageUrl: "https://phonedb.net/img/apple_iphone14_3.jpg",
    images: [
      "https://phonedb.net/img/apple_iphone14_3.jpg",
      "https://imageio.forbes.com/blogs-images/davidphelan/files/2018/04/iPhone8PLUS-PRODUCT-RED_back_041018.jpg?height=852&width=711&fit=bounds",
      "https://imageio.forbes.com/blogs-images/davidphelan/files/2018/04/iPhone8-iPhone8PLUS-PRODUCT-RED_front-back_041018-1200x1440.jpg?format=jpg&width=960",
    ],
    category: "tech",
  },
  {
    id: 2,
    title: "Galaxy A23 5G 2022",
    uploadedDate: new Date(),
    description: `The 5000 mAh battery powers hours of work or play, keeping you going through your day and beyond. Latin American dual SIM 5G NR variant with 4 GiB of RAM and 64 GB flash memory`,
    price: 250,
    sellerName: "Samsung",
    imageUrl: "https://phonedb.net/img/samsung_galaxy_a23_5g_2022.jpg",
    images: [
      "https://phonedb.net/img/samsung_galaxy_a23_5g_2022.jpg",
      "https://m.media-amazon.com/images/I/81Mh6Q5mMuL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/810F32kcAML._AC_SX679_.jpg",
    ],
    category: "tech",
  },
  {
    id: 3,
    title: "Honor 70 5G",
    uploadedDate: new Date(),
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse in dolor imperdiet, tincidunt dui quis, posuere tortor. Duis nec ultrices lectus. Integer dictum, felis eget tempus sagittis, massa ex pretium justo, sed feugiat odio eros quis ante. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin nec hendrerit augue`,
    price: 300,
    sellerName: "Honor",
    imageUrl: "https://phonedb.net/img/huawei_honor_70_2.jpg",
    images: [
      "https://phonedb.net/img/huawei_honor_70_2.jpg",
      "https://m.media-amazon.com/images/I/61WXErkutjL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61PZnXCtTXL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71Nu1PkbeOL._AC_SX679_.jpg",
    ],
    category: "tech",
  },
  {
    id: 4,
    title: "Redmi 11 Prime 5G",
    uploadedDate: new Date(),
    description: `Ut ac turpis non elit suscipit rutrum. Nullam finibus est sed metus viverra egestas. Mauris mollis tincidunt leo, nec facilisis turpis tempor non. Vestibulum lobortis metus ut lectus lacinia euismod. Phasellus tempor, lorem et rhoncus fermentum,`,
    price: 400,
    sellerName: "Xiaomi",
    imageUrl: "https://phonedb.net/img/xiaomi_redmi_11_prime_5g.jpg",
    images: [],
    category: "tech",
  },
  {
    id: 5,
    title: "ZenFone 8z 2021",
    uploadedDate: new Date(),
    description: `Curabitur eget purus magna. Curabitur ullamcorper eros odio, pharetra ornare justo dapibus ac. Donec quis massa porttitor, efficitur felis ac, fermentum nisl. Suspendisse faucibus ex mauris, ac viverra mi fermentum non. Suspendisse sapien risus, pulvinar pulvinar elit vel, rutrum ullamcorper mauris.`,
    price: 2134,
    sellerName: "Asus",
    imageUrl: "https://phonedb.net/img/asus_zenfone_8_2021.jpg",
    images: [],
    category: "tech",
  },
  {
    id: 6,
    title: "Moto g22 2022",
    uploadedDate: new Date(),
    description: `Mauris auctor, eros et aliquam fringilla, elit elit eleifend massa, condimentum tempus urna nulla in arcu. In condimentum pellentesque lectus pulvinar posuere. Nulla risus risus, dictum vel sagittis sed, cursus eu turpis. Vestibulum magna purus, ultrices vel tempor non, bibendum dignissim eros. Etiam posuere, mauris vitae scelerisque ultricies, quam diam pulvinar nibh, a fermentum dolor diam id neque. Sed quis tellus erat. Fusce pretium tristique condimentum.`,
    price: 200,
    sellerName: "Motorola",
    imageUrl: "https://phonedb.net/img/motorola_moto_g22_2022_2.jpg",
    images: ["https://phonedb.net/img/motorola_moto_g22_2022_2.jpg"],
    category: "tech",
  },
];

export const BRANDS = [
  "Apple",
  "Asus",
  "Samsung",
  "Xiaomi",
  "Motorola",
  "Honor",
];
